---
- hosts: all
  tasks:
  - name: yum update
    yum:
      name: '*'
      state: latest
    ignore_errors: yes

  - name: Install java
    yum:
      name: java-11-openjdk-devel
      state: present
    ignore_errors: yes

  - name: Install jenkins
    yum:
      name: jenkins
      state: latest
    ignore_errors: yes

  - name: daemon-reload to pick up config changes
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: Start jenkins
    ansible.builtin.systemd:
      name: jenkins
      state: started
